"""Post-meeting summary email delivery via Resend."""
from __future__ import annotations

import logging
from datetime import datetime
from typing import Any, Dict, List, Optional

import httpx

from app.core.config import settings

_BASE = lambda: settings.FRONTEND_URL  # noqa: E731

logger = logging.getLogger(__name__)

RESEND_API_URL = "https://api.resend.com/emails"


class EmailService:
    def _priority_badge(self, priority: str) -> str:
        colours = {"urgent": "#dc2626", "high": "#ea580c", "medium": "#ca8a04", "low": "#16a34a"}
        colour = colours.get((priority or "medium").lower(), "#6b7280")
        return f'<span style="background:{colour};color:#fff;padding:1px 6px;border-radius:3px;font-size:11px">{priority.upper()}</span>'

    def _build_html(
        self,
        meeting_title: str,
        meeting_id: str,
        scheduled_start: Optional[datetime],
        executive_summary: str,
        decisions: List[Dict[str, Any]],
        action_items: List[Dict[str, Any]],
    ) -> str:
        app_url = f"{_BASE()}/meetings/{meeting_id}"
        date_str = scheduled_start.strftime("%B %d, %Y at %H:%M UTC") if scheduled_start else "N/A"

        decisions_html = ""
        if decisions:
            rows = "".join(
                f"<li style='margin-bottom:6px'><strong>{d.get('decision','')}</strong>"
                + (f" — {d['reasoning']}" if d.get("reasoning") else "")
                + "</li>"
                for d in decisions[:5]
            )
            decisions_html = f"""
            <h3 style="color:#1e293b;margin-top:24px">Key Decisions</h3>
            <ul style="padding-left:18px;color:#334155">{rows}</ul>
            """

        actions_html = ""
        if action_items:
            rows = "".join(
                f"""<tr>
                  <td style="padding:8px 10px;border-bottom:1px solid #e2e8f0">{a.get('title','')}</td>
                  <td style="padding:8px 10px;border-bottom:1px solid #e2e8f0;color:#64748b">{a.get('owner') or '—'}</td>
                  <td style="padding:8px 10px;border-bottom:1px solid #e2e8f0;color:#64748b">{str(a.get('due_date','') or '—')[:10]}</td>
                  <td style="padding:8px 10px;border-bottom:1px solid #e2e8f0">{self._priority_badge(a.get('priority','medium'))}</td>
                </tr>"""
                for a in action_items[:10]
            )
            actions_html = f"""
            <h3 style="color:#1e293b;margin-top:24px">Action Items</h3>
            <table style="width:100%;border-collapse:collapse;font-size:13px">
              <thead>
                <tr style="background:#f1f5f9">
                  <th style="padding:8px 10px;text-align:left;color:#475569">Task</th>
                  <th style="padding:8px 10px;text-align:left;color:#475569">Owner</th>
                  <th style="padding:8px 10px;text-align:left;color:#475569">Due</th>
                  <th style="padding:8px 10px;text-align:left;color:#475569">Priority</th>
                </tr>
              </thead>
              <tbody>{rows}</tbody>
            </table>
            """

        return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:32px 16px">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.1)">
        <!-- Header -->
        <tr><td style="background:#0f172a;padding:24px 32px">
          <p style="margin:0;color:#94a3b8;font-size:12px;text-transform:uppercase;letter-spacing:1px">Post-Meeting Summary</p>
          <h1 style="margin:4px 0 0;color:#fff;font-size:22px">{meeting_title}</h1>
          <p style="margin:6px 0 0;color:#94a3b8;font-size:13px">📅 {date_str}</p>
        </td></tr>
        <!-- Body -->
        <tr><td style="padding:28px 32px">
          <h3 style="color:#1e293b;margin-top:0">Summary</h3>
          <p style="color:#334155;line-height:1.6;margin-top:0">{executive_summary or 'No summary available.'}</p>
          {decisions_html}
          {actions_html}
          <!-- CTA -->
          <div style="margin-top:28px;text-align:center">
            <a href="{app_url}" style="background:#6366f1;color:#fff;text-decoration:none;padding:12px 28px;border-radius:8px;font-weight:600;font-size:14px">View Full Meeting Details →</a>
          </div>
        </td></tr>
        <!-- Footer -->
        <tr><td style="background:#f1f5f9;padding:16px 32px;text-align:center">
          <p style="margin:0;color:#94a3b8;font-size:12px">This summary was auto-generated by SyncMinds. <a href="{app_url}" style="color:#6366f1">View in app</a></p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>"""

    async def send_meeting_summary(
        self,
        recipients: List[str],
        meeting_title: str,
        meeting_id: str,
        scheduled_start: Optional[datetime],
        executive_summary: str,
        decisions: List[Dict[str, Any]],
        action_items: List[Dict[str, Any]],
    ) -> bool:
        api_key = getattr(settings, "RESEND_API_KEY", "")
        if not api_key:
            logger.debug("email: RESEND_API_KEY not set — skipping email summary")
            return False

        from_addr = getattr(settings, "FROM_EMAIL", "noreply@meetingintel.ai")
        html = self._build_html(meeting_title, meeting_id, scheduled_start, executive_summary, decisions, action_items)

        payload = {
            "from": f"SyncMinds <{from_addr}>",
            "to": recipients,
            "subject": f"Meeting Summary: {meeting_title}",
            "html": html,
        }

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.post(
                    RESEND_API_URL,
                    headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
                    json=payload,
                )
            if resp.status_code in (200, 201):
                logger.info("email: summary sent to %d recipients for meeting %s", len(recipients), meeting_id)
                return True
            else:
                logger.warning("email: Resend returned %s: %s", resp.status_code, resp.text[:200])
                return False
        except Exception as exc:
            logger.warning("email: failed to send summary email: %s", exc)
            return False

    async def send_action_item_reminder(
        self,
        recipient_email: str,
        title: str,
        due_date: Optional[str],
        priority: str,
        reminder_type: str,
        action_item_id: str,
    ) -> bool:
        api_key = getattr(settings, "RESEND_API_KEY", "")
        if not api_key:
            return False

        from_addr = getattr(settings, "FROM_EMAIL", "noreply@meetingintel.ai")
        type_labels = {"48h": "due in 48 hours", "day-of": "due today", "overdue": "OVERDUE"}
        label = type_labels.get(reminder_type, reminder_type)
        emoji = "🔴" if reminder_type == "overdue" else ("🟠" if reminder_type == "day-of" else "🟡")

        html = f"""<!DOCTYPE html>
<html><body style="font-family:-apple-system,sans-serif;padding:32px;background:#f8fafc">
  <div style="max-width:480px;margin:0 auto;background:#fff;border-radius:12px;padding:28px;box-shadow:0 1px 3px rgba(0,0,0,.1)">
    <h2 style="margin-top:0;color:#0f172a">{emoji} Action Item Reminder</h2>
    <p style="font-size:16px;font-weight:600;color:#1e293b">{title}</p>
    <p style="color:#64748b">This task is <strong>{label}</strong>.</p>
    {'<p style="color:#64748b">Due: <strong>' + str(due_date)[:10] + '</strong></p>' if due_date else ''}
    <p>Priority: {self._priority_badge(priority)}</p>
    <div style="margin-top:20px">
      <a href="{_BASE()}/action-items/{action_item_id}" style="background:#6366f1;color:#fff;text-decoration:none;padding:10px 20px;border-radius:6px;font-size:14px">View Task →</a>
    </div>
  </div>
</body></html>"""

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.post(
                    RESEND_API_URL,
                    headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
                    json={
                        "from": f"SyncMinds <{from_addr}>",
                        "to": [recipient_email],
                        "subject": f"{emoji} Action Item {label.title()}: {title[:60]}",
                        "html": html,
                    },
                )
            return resp.status_code in (200, 201)
        except Exception as exc:
            logger.warning("email: reminder failed for %s: %s", recipient_email, exc)
            return False


    async def send_absentee_catchup(
        self,
        recipient_email: str,
        meeting_title: str,
        meeting_id: str,
        scheduled_start: Optional[datetime],
        actions_assigned: List[Dict[str, Any]],
        decisions: List[Dict[str, Any]],
        skip_recommendation: Dict[str, Any],
    ) -> bool:
        api_key = getattr(settings, "RESEND_API_KEY", "")
        if not api_key:
            return False

        from_addr = getattr(settings, "FROM_EMAIL", "noreply@meetingintel.ai")
        date_str = scheduled_start.strftime("%B %d, %Y at %H:%M UTC") if scheduled_start else "N/A"
        app_url = f"{_BASE()}/meetings/{meeting_id}"

        actions_html = ""
        if actions_assigned:
            rows = "".join(
                f"<li style='margin-bottom:6px'><strong>{a.get('task','')}</strong>"
                + (f" — due {str(a.get('deadline',''))[:10]}" if a.get("deadline") else "")
                + f" <span style='background:{self._priority_badge(a.get('priority','medium'))};color:#fff;padding:1px 5px;border-radius:3px;font-size:11px'>{(a.get('priority','medium')).upper()}</span>"
                + "</li>"
                for a in actions_assigned[:5]
            )
            actions_html = f"<h3 style='color:#1e293b;margin-top:20px'>⚡ Action Items Assigned to You</h3><ul style='padding-left:18px;color:#334155'>{rows}</ul>"

        decisions_html = ""
        if decisions:
            rows = "".join(
                f"<li style='margin-bottom:6px;color:#334155'>{d.get('decision','') or d.get('text','')}</li>"
                for d in decisions[:5]
            )
            decisions_html = f"<h3 style='color:#1e293b;margin-top:20px'>🔑 Decisions That May Affect Your Work</h3><ul style='padding-left:18px'>{rows}</ul>"

        skip_html = ""
        rec = skip_recommendation.get("recommendation", "")
        if rec == "safe_to_skip":
            skip_html = "<div style='margin-top:16px;padding:10px 14px;background:#f0fdf4;border-left:3px solid #22c55e;border-radius:4px;color:#166534;font-size:13px'>✅ Safe to skip future similar meetings</div>"
        elif rec == "should_attend":
            skip_html = "<div style='margin-top:16px;padding:10px 14px;background:#fef2f2;border-left:3px solid #ef4444;border-radius:4px;color:#991b1b;font-size:13px'>⚠️ You should attend next time — important decisions were made that affect your work.</div>"

        html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:32px 16px">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.1)">
        <tr><td style="background:#0f172a;padding:24px 32px">
          <p style="margin:0;color:#94a3b8;font-size:12px;text-transform:uppercase;letter-spacing:1px">You missed a meeting</p>
          <h1 style="margin:4px 0 0;color:#fff;font-size:22px">{meeting_title}</h1>
          <p style="margin:6px 0 0;color:#94a3b8;font-size:13px">📅 {date_str}</p>
        </td></tr>
        <tr><td style="padding:28px 32px">
          <p style="color:#475569;margin-top:0">Here's a personalised catch-up of what happened and what you need to action.</p>
          {actions_html}
          {decisions_html}
          {skip_html}
          <div style="margin-top:28px;text-align:center">
            <a href="{app_url}" style="background:#6366f1;color:#fff;text-decoration:none;padding:12px 28px;border-radius:8px;font-weight:600;font-size:14px">View Full Meeting →</a>
          </div>
        </td></tr>
        <tr><td style="background:#f1f5f9;padding:16px 32px;text-align:center">
          <p style="margin:0;color:#94a3b8;font-size:12px">Auto-generated by SyncMinds · <a href="{app_url}" style="color:#6366f1">View in app</a></p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>"""

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.post(
                    RESEND_API_URL,
                    headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
                    json={
                        "from": f"SyncMinds <{from_addr}>",
                        "to": [recipient_email],
                        "subject": f"You missed: {meeting_title}",
                        "html": html,
                    },
                )
            if resp.status_code in (200, 201):
                logger.info("email: absentee catch-up sent to %s", recipient_email)
                return True
            logger.warning("email: Resend returned %s for absentee email", resp.status_code)
            return False
        except Exception as exc:
            logger.warning("email: absentee catch-up failed for %s: %s", recipient_email, exc)
            return False


email_service = EmailService()
